// <auto-generated />
using System;
using Bakery.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bakery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210328064110_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bakery.Core.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerName")
                        .HasName("IDX_CUSTOMER_NAME");

                    b.HasIndex("DateEnd");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Bakery.Core.Entities.CustomerAddress", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AddressName")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Latitude")
                        .HasColumnType("float(10,6)");

                    b.Property<float>("Longitude")
                        .HasColumnType("float(10,6)");

                    b.HasKey("AddressId")
                        .HasName("PRIMARY");

                    b.HasIndex("DateEnd");

                    b.HasIndex("CustomerId", "AddressId")
                        .IsUnique()
                        .HasName("Customer_AddressId_UNIQUE");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("Bakery.Core.Entities.CustomerDiscount", b =>
                {
                    b.Property<long>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("DiscountId")
                        .HasName("PRIMARY");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DateEnd");

                    b.HasIndex("DiscountId", "CustomerId")
                        .IsUnique()
                        .HasName("CustomerId_DiscountId_UNIQUE");

                    b.ToTable("CustomerDiscount");
                });

            modelBuilder.Entity("Bakery.Core.Entities.DiscountTime", b =>
                {
                    b.Property<long>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("DayWeek")
                        .HasColumnType("int(11)");

                    b.Property<long>("DiscountId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("EndTime")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("StartTime")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TimeId")
                        .HasName("PRIMARY");

                    b.HasIndex("DiscountId")
                        .HasName("FK_DISCOUNT_TIMES_DISCOUNT");

                    b.HasIndex("TimeId", "DiscountId")
                        .IsUnique()
                        .HasName("DiscountId_TimeId_UNIQUE");

                    b.ToTable("DiscountTime");
                });

            modelBuilder.Entity("Bakery.Core.Entities.CustomerAddress", b =>
                {
                    b.HasOne("Bakery.Core.Entities.Customer", "Customer")
                        .WithMany("CustomerAddress")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_CUSTOMER_ADDRESS_CUSTOMER")
                        .IsRequired();
                });

            modelBuilder.Entity("Bakery.Core.Entities.CustomerDiscount", b =>
                {
                    b.HasOne("Bakery.Core.Entities.Customer", "Customer")
                        .WithMany("CustomerDiscount")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_DISCOUNT_CUSTOMER")
                        .IsRequired();
                });

            modelBuilder.Entity("Bakery.Core.Entities.DiscountTime", b =>
                {
                    b.HasOne("Bakery.Core.Entities.CustomerDiscount", "Discount")
                        .WithMany("DiscountTime")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_DISCOUNT_TIMES_DISCOUNT")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
